global:
  resolve_timeout: 5m

route:
  receiver: "discord-webhook"
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: "discord-webhook"
    discord_configs:
      - webhook_url: "<ë””ìŠ¤ì½”ë“œ ì›¹í›… URL>"
        send_resolved: false
        title: "**ğŸš¨ [{{ .CommonLabels.alertname }}] ë°œìƒ! ğŸš¨**"
        content: |
          **ğŸ”¹ ì¸ìŠ¤í„´ìŠ¤:** {{ .CommonLabels.instance }}
          **âš ï¸ ì‹¬ê°ë„:** {{ .CommonLabels.severity }}
          **ğŸ›  ì„¤ëª…:** {{ .CommonAnnotations.description }}
          **ğŸ”” ì•ŒëŒë„ëŸ¬ê°€ê¸°:** <Alertmanager URL>
        username: "Hot6ë¹„ìƒ!!"